<div style="text-align: center;">

$$\huge \textcolor{red}{\textbf{ESCUELA POLITÉCNICA NACIONAL}}$$  
<br><br>

$$\Large \textcolor{brown}{\textbf{Facultad de Ingeniería en Sistemas}}$$  
$$\Large \textcolor{brown}{\textbf{Ingeniería en Ciencias Computacionales}}$$  
$$\Large \textcolor{brown}{\textbf{Métodos Numéricos}}$$  
$$\Large \textcolor{brown}{\textbf{Segundo Bimestre}}$$ 

<br><br>

<img src="https://news.cnrs.fr/sites/default/files/styles/visuel_principal/public/assets/images/adobestock_252860172_vp.jpg?itok=azu_-20J" width="600"/>

<br><br>

$$\Large \textcolor{red}{\textbf{Estudiante:}}$$  
$$\Large \textbf{Estéfano Condoy}$$  

<br>

$$\Large \textcolor{red}{\textbf{Docente:}}$$  
$$\Large \textbf{Carlos Ayala}$$  

<br>

$$\Large \textcolor{red}{\textbf{Semestre:}}$$  
$$\Large \textbf{25-A}$$  

</div>

<div style="page-break-after: always;"></div>


<div style="text-align: center;">

$$\huge \textcolor{red}{\textbf{U5 Eliminación Gaussiana y Gauss-Jordan A}}$$  
<br><br>

# <span style="color:red"><strong>Eliminación Gaussiana</strong></span>

- Este método sirve para resolver sistemas de ecuaciones lineales, basado en la aplicación de operaciones elementales sobre las filas de una matriz aumentada. 

- El objetivo de la eliminación Gaussiana es transformar el sistema original en uno equivalente con estructura triangular superior ya que este facilita la obtención de las incognitas con sustituciones hacia atrás.

- Este método es uno de los pilares en esta materia  y es ampliamente utilizado por su claridad y 
aplicabilidad. 
- En esta implementación, se utiliza aritmética de 32 bits para simular el comportamiento de los 
cálculos en una computadora, además de medir el tiempo real de ejecución y el tiempo de procesamiento del sistema.



A continuación se observara el código comentado para que se pueda entender lo que realice para codificar la eliminación Gaussiana:

In [ ]:
# @autor: Estefano Condoy
# @fecha: 2025-06-30
# @versión: 1.0
# @asignatura: Métodos Numéricos
# @código ralizado basado en el pseudocódigo del Ing. Carlos Ayala

import numpy as np    # Lo utilizamos solo para la conversión de aritmetica computacional de 32 bits
import time  # Esto lo utilizamos solo para medir el tiempo de ejecución
import os    # Esto lo utilizamos solo para medir el tiempo de procesamiento 

def Ec_eliminacion_gaussiana(Ec_A):
    """
    Lo que nuestro código hace es resolver un sistema lineal Ec_Ax = b mediante eliminación gaussiana (precisión 32 bits).
    Para esto utilizamos los siguientes paramentros:
    
    Ec_A: matriz aumentada tipo numpy.array de tamaño (n x n+1) y dtype=float32
    :return: vector solución x si existe, o mensaje indicando que no hay solución única
    """

    # Con esto iniciamos el tiempo en el cronómetro y tiempo de CPU
    Ec_tiempo_inicio = time.time()
    Ec_cpu_inicio = os.times()[0]

    # Con esta linea aseguramos que la matriz este en precisión de 32 bits.
    Ec_A = Ec_A.astype(np.float32)

    # Obtenemos el numero de ecuaciones.
    Ec_n = Ec_A.shape[0]

    # En el paso 1 hacemos la eliminación gaussiana hacia adelante.
    for Ec_i in range(Ec_n - 1):
        # En el paso dos buscamos el renglon o una posición de las otras filas distinto a 0
        Ec_p = -1
        for Ec_k in range(Ec_i, Ec_n):
            if Ec_A[Ec_k][Ec_i] != 0:
                Ec_p = Ec_k
                break

        # Si no se encontró ningún pivote válido, no hay solución única
        if Ec_p == -1:
            print("SALIDA: no existe una solución única (columna sin pivote)")
            return None

        # En el paso tres intercambiamos fila si es necesario para que nos quede el pivote en la posición correcta
        if Ec_p != Ec_i:
            Ec_A[[Ec_i, Ec_p]] = Ec_A[[Ec_p, Ec_i]]

        # En el paso 4 hasta el 6 eliminamos segun el proceso matematica en la columna actual.
        for Ec_j in range(Ec_i + 1, Ec_n):
            # En el paso 5 calculamos el multiplicador (Ec_mji)
            Ec_mji = Ec_A[Ec_j][Ec_i] / Ec_A[Ec_i][Ec_i]

            # En el paso 6 restamos m_ji * fila_i a fila_j
            Ec_A[Ec_j] = Ec_A[Ec_j] - Ec_mji * Ec_A[Ec_i]

    # En el paso 7 verificamos si el último pivote
    if Ec_A[Ec_n - 1][Ec_n - 1] == 0:
        print("SALIDA: no existe una solución única (último pivote es 0)")
        return None

    # En paso 8 al ya esta la elminación gaussiana hacia adelante, procedemos a resolver el sistema (Sustitución hacia atrás).
    Ec_x = np.zeros(Ec_n, dtype=np.float32)  # Solución final
    Ec_x[Ec_n - 1] = Ec_A[Ec_n - 1][Ec_n] / Ec_A[Ec_n - 1][Ec_n - 1]

    # En el paso 9 resolvemos cada incógnita desde la penúltima hacia la primera
    for Ec_i in range(Ec_n - 2, -1, -1):
        Ec_suma = np.float32(0.0)
        for Ec_j in range(Ec_i + 1, Ec_n):
            Ec_suma += Ec_A[Ec_i][Ec_j] * Ec_x[Ec_j]
        Ec_x[Ec_i] = (Ec_A[Ec_i][Ec_n] - Ec_suma) / Ec_A[Ec_i][Ec_i]

    # Aquí finalizamos el cronómetro y tiempo de procesamiento 
    Ec_tiempo_fin = time.time()
    Ec_cpu_fin = os.times()[0]

    # Resultado y métricas
    print("SALIDA: Ec_x =", Ec_x)
    print(f"Tiempo de ejecución real: {Ec_tiempo_fin - Ec_tiempo_inicio:.6f} segundos")
    print(f"Tiempo de procesamiento : {Ec_cpu_fin - Ec_cpu_inicio:.6f} segundos")

    return Ec_x


A continuación un ejemplo (Pueden editar con cualquier matriz):

In [28]:
# Ejemplo: sistema de 3 ecuaciones y 3 incógnitas
Ec_matriz_aumentada = np.array([
    [1/4, 1/5, 1/6, 9],
    [1/3, 1/4, 1/5, 8],
    [1/2, 1, 2, 8]
], dtype=np.float32)

Ec_solucion = Ec_eliminacion_gaussiana(Ec_matriz_aumentada)


SALIDA: Ec_x = [-227.07666  476.92264 -177.69217]
Tiempo de ejecución real: 0.000066 segundos
Tiempo de procesamiento : 0.000000 segundos


# <span style="color:red"><strong>Eliminación Gauss-Jordan</strong></span>

- Este método es una extensión del método gaussianp que permite resolver sistemas, pero la diferencia es que este método n necesita la sustitución hacia atrás porque la matriz se convierte directamente en una forma en la que cada variable tiene un unico valor(una diagonal de 1 en varias ocaciones).

- Este procedimiento se basa en operaciones elementales sobre filas para obtener una matriz identidad en la parte de coeficientes y así obtener la solución del sistema directamente. 
- Este método es mas trabajado porque tiene  más operaciones pero nos da la ventaja de darnos la solucion directamente.

A continuación se observara el código comentado para que se pueda entender lo que realice para codificar la eliminación de Gauss-Jordan:

In [32]:
# @autor: Estefano Condoy
# @fecha: 2025-07-01
# @versión: 1.0
# @asignatura: Métodos Numéricos


import numpy as np # Lo utilizamos solo para la conversión de aritmetica computacional de 32 bits
import time # Esto lo utilizamos solo para medir el tiempo de ejecución
import os  # Esto lo utilizamos solo para medir el tiempo de procesamiento

def Ec_gauss_jordan(Ec_A):
    """
    Lo que nuestro código hace es resolver un sistema lineal Ec_Ax = b usando eliminación Gauss-Jordan. (precisión 32 bits).
    Para esto utilizamos los siguientes paramentros:
    Ec_A: matriz aumentada de tipo numpy.array con dtype=float32, tamaño (n, n+1)
    :return: vector solución x si existe, o mensaje de error
    """

    # Aquí iniciamos el cronómetro y tiempo procesamiento
    Ec_tiempo_inicio = time.time()
    Ec_cpu_inicio = os.times()[0]

    # Convertimos a precisión de 32 bits
    Ec_A = Ec_A.astype(np.float32)
    Ec_n = Ec_A.shape[0]

    for Ec_i in range(Ec_n):
        # En el paso 1 verificamos que el pivote no sea cero, buscar fila con pivote válido
        if Ec_A[Ec_i][Ec_i] == 0:
            Ec_p = -1
            for Ec_k in range(Ec_i + 1, Ec_n):
                if Ec_A[Ec_k][Ec_i] != 0:
                    Ec_p = Ec_k
                    break
            if Ec_p == -1:
                print("SALIDA: no existe solución única (columna sin pivote)")
                return None
            Ec_A[[Ec_i, Ec_p]] = Ec_A[[Ec_p, Ec_i]]  # Hacemos intercambio de filas si es necesario

        #  En el paso 2 normalizamos la fila actual para que el pivote sea 1
        Ec_A[Ec_i] = Ec_A[Ec_i] / Ec_A[Ec_i][Ec_i]

        # En el paso 3 hacemos 0 en todas las otras filas menos en la actual.
        for Ec_j in range(Ec_n):
            if Ec_j != Ec_i:
                Ec_factor = Ec_A[Ec_j][Ec_i]
                Ec_A[Ec_j] = Ec_A[Ec_j] - Ec_factor * Ec_A[Ec_i]

    # Con esta linea extraemos la solución del sistema
    Ec_x = Ec_A[:, -1]

    # Finalizamos el cronómetro y tiempo de procesamiento
    Ec_tiempo_fin = time.time()
    Ec_cpu_fin = os.times()[0]

    # Resultado y métricas

    print("SALIDA: x =", Ec_x)
    print(f"Tiempo de ejecución real: {Ec_tiempo_fin - Ec_tiempo_inicio:.6f} segundos")
    print(f"Tiempo de procesamiento: {Ec_cpu_fin - Ec_cpu_inicio:.6f} segundos")
    return Ec_x
# 

A continuación un ejemplo (Pueden editar con cualquier matriz):

In [33]:
Ec_matriz_aumentada = np.array([
    [1/4, 1/5, 1/6, 9],
    [1/3, 1/4, 1/5, 8],
    [1/2, 1, 2, -8]
], dtype=np.float32)

Ec_solucion = Ec_gauss_jordan(Ec_matriz_aumentada)


SALIDA: x = [-234.46127  501.53796 -196.15369]
Tiempo de ejecución real: 0.000143 segundos
Tiempo de procesamiento: 0.000000 segundos


$$\huge \textcolor{red}{\textbf{U5 Descomposición LU B}}$$ 

# <span style="color:red"><strong>Descomposición LU, método matriz inversa</strong></span>

La **descomposición LU** permite expresar una matriz cuadrada $A$ como el producto de dos matrices: una matriz triangular inferior $L$ y una matriz triangular superior $U$, es decir:

$$
A = L \cdot U
$$

Este tipo de descomposición es ampliamente utilizado para:

- Resolver sistemas de ecuaciones lineales
- Calcular determinantes
- Invertir matrices de manera eficiente

Se utiliza un enfoque basado en **matrices elementales inversas**.
- Primero en la matriz inversa se hace eliminación gaussiana, se generan matrices elementales $E_1, E_2, \ldots, E_k$ que representan cada operación de fila 
utilizada para anular los elementos por debajo de la diagonal de $A$.




# <span style="color:red"><strong>Método de la matriz inversa</strong></span>

Se tiene un sistema lineal:

$$
Ax = b
$$

Multiplicamos ambos lados por la inversa de la matriz \( A \):

$$
A^{-1}Ax = A^{-1}b
$$

Sabemos que \( A^{-1}A = I \), por lo tanto:

$$
Ix = A^{-1}b
$$

Finalmente, como \( I \) es la matriz identidad:

$$
x = A^{-1}b
$$


A continuación se observara el código comentado para que se pueda entender lo que realice para mi codificación:

In [15]:
# @autor: Estefano Condoy
# @fecha: 2025-07-01
# @versión: 1.1
# @asignatura: Métodos Numéricos

import numpy as np    # Lo utilizaremos solo para crear arreglos y matrices
import time           # Esto lo utilizamos solo para medir el tiempo de ejecución
import os             # Esto lo utilizamos solo para medir el tiempo de procesamiento 

def Ec_descomposicion_LU_inversa(Ec_A):
    """
    Mi código realiza la descomposición LU de una matriz cuadrada usando el método de matrices inversas.
    Mi código devolverá matrices  L (triangular inferior) y U (triangular superior) y su Verificación (o sea su multiplicación).

    Los parámetros son:
    - Ec_A: matriz cuadrada tipo numpy.array (n x n)

    Su retorno es:
    - Matriz L (triangular inferior)
    - Matriz U (triangular superior)
    """

    # Antes de iniciar a codificar ponemos el cronómetro y tiempo de CPU para medir el tiempo de ejecución
    Ec_tiempo_inicio = time.time()
    Ec_cpu_inicio = os.times()[0]

    # Verificación: la matriz debe ser cuadrada (número de filas igual a columnas)
    if Ec_A.shape[0] != Ec_A.shape[1]:
        print("SALIDA: La matriz no es cuadrada, no se puede descomponer con este método.")
        return None, None

    # En el primer paso copiamos la matriz original 
    Ec_A = Ec_A.copy()
    Ec_n = Ec_A.shape[0]  # Aquí se decide el número de filas y columnas

    # En el paso 2 inicializamos la matriz L⁻¹ como identidad, y U como una copia de A
    Ec_L_inv = np.identity(Ec_n)
    Ec_U = Ec_A.copy()

    # En el paso 3 realizamos la eliminación Gaussiana pero se guardan las matrices elementales inversas
    for Ec_i in range(Ec_n - 1):
        # Verificamos que el pivote no sea cero
        if Ec_U[Ec_i][Ec_i] == 0:
            print("SALIDA: Pivote cero en la posición", Ec_i, ", no se puede continuar")
            return None, None

        for Ec_j in range(Ec_i + 1, Ec_n):
            # Calculamos el multiplicador m_ji
            Ec_mji = Ec_U[Ec_j][Ec_i] / Ec_U[Ec_i][Ec_i]

            # Creamos la matriz inversa (para restar m_ji · fila_i a fila_j)
            Ec_E = np.identity(Ec_n)
            Ec_E[Ec_j][Ec_i] = -Ec_mji

            # Aplicamos esta operación a U (fila_j ← fila_j - m_ji · fila_i)
            Ec_U = Ec_E @ Ec_U  # El @ es el operador de producto matricial en numpy

            # Aquí acumulamos la operación en L⁻¹
            Ec_L_inv = Ec_E @ Ec_L_inv

    # Aquí invertimos L⁻¹ para obtener L
    Ec_L = np.linalg.inv(Ec_L_inv)

    # Aquí detenemos el cronómetro y tiempo de procesamiento.
    Ec_tiempo_fin = time.time()
    Ec_cpu_fin = os.times()[0]

    # Mostramos los resultados y métricas
    print("SALIDA: Ec_Matriz L =\n", Ec_L)
    print("SALIDA: Ec_Matriz U =\n", Ec_U)
    print("VERIFICACIÓN: L · U =\n", Ec_L @ Ec_U)
    print(f"Tiempo de ejecución real: {Ec_tiempo_fin - Ec_tiempo_inicio:.6f} segundos")
    print(f"Tiempo de procesamiento : {Ec_cpu_fin - Ec_cpu_inicio:.6f} segundos")

    return Ec_L, Ec_U


A continuación un ejemplo (Pueden editar con cualquier matriz):

In [16]:
Ec_A = np.array([
    [2, -1, 1],
    [-3, 3, 9],
    [6, -6, -6]
])

Ec_L, Ec_U = Ec_descomposicion_LU_inversa(Ec_A)


SALIDA: Ec_Matriz L =
 [[ 1.   0.   0. ]
 [-1.5  1.   0. ]
 [ 3.  -2.   1. ]]
SALIDA: Ec_Matriz U =
 [[ 2.  -1.   1. ]
 [ 0.   1.5 10.5]
 [ 0.   0.  12. ]]
VERIFICACIÓN: L · U =
 [[ 2. -1.  1.]
 [-3.  3.  9.]
 [ 6. -6. -6.]]
Tiempo de ejecución real: 0.000143 segundos
Tiempo de procesamiento : 0.000000 segundos


# <span style="color:red"><strong>Descomposición LU, producto de matrices</strong></span>


Este método es útil para resolver sistemas de ecuaciones lineales de la forma:  
$$
A \mathbf{x} = \mathbf{b}
$$

Multiplicando ambos lados por la inversa de \( A \), se tiene que:  
$$
A^{-1} A \mathbf{x} = A^{-1} \mathbf{b}
$$  
lo que implica  
$$
\mathbf{x} = A^{-1} \mathbf{b}
$$

Sin embargo, calcular $$ A^{-1} $$ explícitamente es computacionalmente costoso y numéricamente inestable. Por ello, la descomposición LU permite resolver el sistema mediante dos pasos:  
1. Se resuelve usando sustitución hacia adelante, y luego  
$$
L \mathbf{y} = \mathbf{b}
$$  

2. Se resuelve usando sustitución hacia atrás.
$$
U \mathbf{x} = \mathbf{y}
$$  


Mi código  continuación implementa este proceso de descomposición LU mediante eliminación gaussiana, seguido de la resolución del sistema y la validación de los resultados:


In [17]:
# @autor: Estefano Condoy
# @fecha: 2025-07-01
# @versión: 1.3
# @asignatura: Métodos Numéricos

import numpy as np    # Lo utilizamos solo para crear arreglos y matrices
import time           # Para medir el tiempo de ejecución real
import os             # Para medir el tiempo de CPU del proceso

def Ec_descomposicion_LU_y_resolver(Ec_A, Ec_b):
    """
    Mi código realiza:
    - La descomposición LU de una matriz cuadrada A, es decir A = L · U, tambien resuelve el sistema A · x = b usando LUx = b
    - Y verifica que L · U = A y que A · x ≈ b

    Mis parámetros son:
    - Ec_A: matriz cuadrada (n x n)
    - Ec_b: vector columna (n x 1) o arreglo (n,)

    Lo que va a retonrar es:
    - Matriz L
    - Matriz U
    - Vector solución x
    """

    # Antes de inciar a codificar ponemos el cronómetro y tiempo de CPU para medir el tiempo de ejecución
    Ec_tiempo_inicio = time.time()
    Ec_cpu_inicio = os.times()[0]

    # En el primer paso verificamos que A sea cuadrada y compatible con b
    if Ec_A.shape[0] != Ec_A.shape[1]:
        print("SALIDA: La matriz A no es cuadrada, no se puede descomponer con este método.")
        return None, None, None

    if Ec_A.shape[0] != Ec_b.shape[0]:
        print("SALIDA: Las dimensiones de A y b no son compatibles.")
        return None, None, None

    # En el paso dos hacemos unas copias de trabajo de A y b, es necesario para no modificar las originales
    Ec_A = Ec_A.copy()
    Ec_b = Ec_b.copy()
    Ec_b = Ec_b.flatten()  # <-- Aquí convertimos a vector 1D para evitar problemas
    Ec_n = Ec_A.shape[0]

    # En el paso tres inicializamos L⁻¹ como identidad, U como A
    Ec_L_inv = np.identity(Ec_n)
    Ec_U = Ec_A.copy()

    # En el paso 4 utilizamos la eliliminación Gaussiana
    for Ec_i in range(Ec_n - 1):
        if Ec_U[Ec_i][Ec_i] == 0:
            print("SALIDA: Pivote cero en la posición", Ec_i, ", no se puede continuar.")
            return None, None, None

        for Ec_j in range(Ec_i + 1, Ec_n):
            Ec_mji = Ec_U[Ec_j][Ec_i] / Ec_U[Ec_i][Ec_i]

            Ec_E = np.identity(Ec_n)
            Ec_E[Ec_j][Ec_i] = -Ec_mji

            Ec_U = Ec_E @ Ec_U
            Ec_L_inv = Ec_E @ Ec_L_inv

    # En el paso 5 invertimos L⁻¹ para obtener L
    Ec_L = np.linalg.inv(Ec_L_inv)

    # En el paso 6 ya hacemos la sustitución hacia adelante (Ly = b)
    Ec_y = np.zeros(Ec_n)
    for Ec_i in range(Ec_n):
        Ec_suma = 0
        for Ec_j in range(Ec_i):
            Ec_suma += Ec_L[Ec_i][Ec_j] * Ec_y[Ec_j]
        Ec_y[Ec_i] = (Ec_b[Ec_i] - Ec_suma) / Ec_L[Ec_i][Ec_i]

    # Aqui en el paso 7 tambien hacemos la sustitución hacia atrás (Ux = y)
    Ec_x = np.zeros(Ec_n)
    for Ec_i in range(Ec_n - 1, -1, -1):
        Ec_suma = 0
        for Ec_j in range(Ec_i + 1, Ec_n):
            Ec_suma += Ec_U[Ec_i][Ec_j] * Ec_x[Ec_j]
        Ec_x[Ec_i] = (Ec_y[Ec_i] - Ec_suma) / Ec_U[Ec_i][Ec_i]

    # Verificamos 
    Ec_LU = Ec_L @ Ec_U #El @ es el operador de producto matricial en numpy
    Ec_Ax = Ec_A @ Ec_x

    # Finalizamos el cronometro y tiempo de procesamiento
    Ec_tiempo_fin = time.time()
    Ec_cpu_fin = os.times()[0]

    # Mostramos los resultados y métricas
    print("SALIDA: Ec_Matriz L =\n", Ec_L)
    print("SALIDA: Ec_Matriz U =\n", Ec_U)
    print("PRODUCTO: L · U =\n", Ec_LU)
    print("VECTOR solución x =\n", Ec_x)
    print("VERIFICACIÓN: A · x =\n", Ec_Ax)
    print("VECTOR original b =\n", Ec_b)
    print(f"Tiempo de ejecución real: {Ec_tiempo_fin - Ec_tiempo_inicio:.6f} segundos")
    print(f"Tiempo de procesamiento : {Ec_cpu_fin - Ec_cpu_inicio:.6f} segundos")

    return Ec_L, Ec_U, Ec_x

A continuación un ejemplo (Pueden editar con cualquier matriz):

In [18]:
Ec_A = np.array([
    [2, -1, 1],
    [-3, 3, 9],
    [6, -6, -6]
])

Ec_b = np.array([2, -1, 3])

Ec_L, Ec_U, Ec_x = Ec_descomposicion_LU_y_resolver(Ec_A, Ec_b)



SALIDA: Ec_Matriz L =
 [[ 1.   0.   0. ]
 [-1.5  1.   0. ]
 [ 3.  -2.   1. ]]
SALIDA: Ec_Matriz U =
 [[ 2.  -1.   1. ]
 [ 0.   1.5 10.5]
 [ 0.   0.  12. ]]
PRODUCTO: L · U =
 [[ 2. -1.  1.]
 [-3.  3.  9.]
 [ 6. -6. -6.]]
VECTOR solución x =
 [1.33333333 0.75       0.08333333]
VERIFICACIÓN: A · x =
 [ 2. -1.  3.]
VECTOR original b =
 [ 2 -1  3]
Tiempo de ejecución real: 0.000143 segundos
Tiempo de procesamiento : 0.000000 segundos


$$\huge \textcolor{red}{\textbf{U5 Gauss Jacobi y Seidel C}}$$ 

## <span style="color:red"><strong>Método Doolittle</strong></span>
Factoriza una matriz \( A \) como  
$$
A = L \times U
$$  
donde \( L \) es triangular inferior con diagonal igual a 1, y \( U \) es triangular superior.

A continuación se observara el código comentado para que se pueda entender lo que realice para mi codificación:

In [51]:
# @autor: Estefano Condoy
# @fecha: 2025-07-03
# @versión: 1.0
# @asignatura: Métodos Numéricos

def Ec_LU_doolittle(Ec_matriz):
    """
    Mi código realiza la Descomposición LU por el método de Doolittle.
    Y este también valida que la matriz sea cuadrada y que no tenga pivotes cero.
    """
    Ec_n = len(Ec_matriz)

    # Primero verificamos que la matriz sea cuadrada para continuar.
    for Ec_fila in Ec_matriz:
        if len(Ec_fila) != Ec_n:
            print("SALIDA: La matriz no es cuadrada.")
            return None

    Ec_L = [[0 for _ in range(Ec_n)] for _ in range(Ec_n)]
    Ec_U = [[0 for _ in range(Ec_n)] for _ in range(Ec_n)]

    for Ec_i in range(Ec_n):
        # Calculamos U
        for Ec_j in range(Ec_i, Ec_n):
            Ec_suma = 0
            for Ec_k in range(Ec_i):
                Ec_suma += Ec_L[Ec_i][Ec_k] * Ec_U[Ec_k][Ec_j]
            Ec_U[Ec_i][Ec_j] = Ec_matriz[Ec_i][Ec_j] - Ec_suma

        # Validamos que el pivote no sea 0
        if Ec_U[Ec_i][Ec_i] == 0:
            print("SALIDA: Pivote cero encontrado. No se puede continuar con Doolittle.")
            return None

        # Calculamos L
        for Ec_j in range(Ec_i, Ec_n):
            if Ec_i == Ec_j:
                Ec_L[Ec_i][Ec_i] = 1
            else:
                Ec_suma = 0
                for Ec_k in range(Ec_i):
                    Ec_suma += Ec_L[Ec_j][Ec_k] * Ec_U[Ec_k][Ec_i]
                Ec_L[Ec_j][Ec_i] = (Ec_matriz[Ec_j][Ec_i] - Ec_suma) / Ec_U[Ec_i][Ec_i]

    #Retornamos las matrices L y U
    return Ec_L, Ec_U


A continuación un ejemplo (Pueden editar con cualquier matriz):

In [52]:
# Ejemplo de descomposición LU por Doolittle
Ec_A = [
    [2, -1, 1],
    [-3, 3, 9],
    [6, -6, -6]
]

Ec_L, Ec_U = Ec_LU_doolittle(Ec_A)

if Ec_L is not None and Ec_U is not None:
    print("SALIDA: Descomposición LU por Doolittle")
    print("Ec_L:")
    for Ec_fila in Ec_L:
        print(Ec_fila)
    print("Ec_U:")
    for Ec_fila in Ec_U:
        print(Ec_fila)


SALIDA: Descomposición LU por Doolittle
Ec_L:
[1, 0, 0]
[-1.5, 1, 0]
[3.0, -2.0, 1]
Ec_U:
[2, -1, 1]
[0, 1.5, 10.5]
[0, 0, 12.0]


## <span style="color:red"><strong>Método Crout</strong></span>
Factoriza \( A \) como  
$$
A = L \times U
$$  
donde \( L \) es triangular inferior con diagonales generales, y \( U \) es triangular superior con diagonal igual a 1.


A continuación se observara el código comentado para que se pueda entender lo que realice para mi codificación:

In [53]:
# @autor: Estefano Condoy
# @fecha: 2025-07-03
# @versión: 1.0
# @asignatura: Métodos Numéricos
# @código basado en el pseudocódigo del Ing. Carlos Ayala

def Ec_LU_crout(Ec_matriz):
    """
    Mi código realiza la Descomposición LU por el método de Crout.
    Y también valida que la matriz sea cuadrada y que no tenga pivotes cero.
    """
    Ec_n = len(Ec_matriz)

    # Verificamos que la matriz sea cuadrada para continuar.
    for Ec_fila in Ec_matriz:
        if len(Ec_fila) != Ec_n:
            print("SALIDA: La matriz no es cuadrada.")
            return None

    Ec_L = [[0 for _ in range(Ec_n)] for _ in range(Ec_n)]
    Ec_U = [[0 for _ in range(Ec_n)] for _ in range(Ec_n)]

    for Ec_i in range(Ec_n):
        Ec_U[Ec_i][Ec_i] = 1

        # Calculamos U
        for Ec_j in range(Ec_i, Ec_n):
            Ec_suma = 0
            for Ec_k in range(Ec_i):
                Ec_suma += Ec_L[Ec_j][Ec_k] * Ec_U[Ec_k][Ec_i]
            Ec_L[Ec_j][Ec_i] = Ec_matriz[Ec_j][Ec_i] - Ec_suma

        # Validamos que el pivote de L no sea cero
        if Ec_L[Ec_i][Ec_i] == 0:
            print("SALIDA: Pivote cero encontrado. No se puede continuar con Crout.")
            return None

        # Calculamos U
        for Ec_j in range(Ec_i + 1, Ec_n):
            Ec_suma = 0
            for Ec_k in range(Ec_i):
                Ec_suma += Ec_L[Ec_i][Ec_k] * Ec_U[Ec_k][Ec_j]
            Ec_U[Ec_i][Ec_j] = (Ec_matriz[Ec_i][Ec_j] - Ec_suma) / Ec_L[Ec_i][Ec_i]

    # Retornamos las matrices L y U
    return Ec_L, Ec_U



A continuación un ejemplo (Pueden editar con cualquier matriz):

In [54]:

# Ejemplo de descomposición LU por Crout
Ec_A = [
    [2, -1, 1],
    [-3, 3, 9],
    [6, -6, -6]
]

Ec_L, Ec_U = Ec_LU_crout(Ec_A)

if Ec_L is not None and Ec_U is not None:
    print("SALIDA: Descomposición LU por Crout")
    print("Ec_L:")
    for Ec_fila in Ec_L:
        print(Ec_fila)
    print("Ec_U:")
    for Ec_fila in Ec_U:
        print(Ec_fila)



SALIDA: Descomposición LU por Crout
Ec_L:
[2, 0, 0]
[-3, 1.5, 0]
[6, -3.0, 12.0]
Ec_U:
[1, -0.5, 0.5]
[0, 1, 7.0]
[0, 0, 1]


## <span style="color:red"><strong>Método Cholesky</strong></span>
Para matrices simétricas y definidas positivas, se factoriza  
$$
A = L \times L^T
$$  
donde \( L \) es triangular inferior, y \( L^T \) su traspuesta.

A continuación se observara el código comentado para que se pueda entender lo que realice para mi codificación:

In [57]:
def Ec_cholesky(Ec_matriz):
    """
    Mi código realiza la Descomposición de Cholesky.
    Solo válida si la matriz es simétrica y definida positiva.
    Devuelve una matriz triangular inferior L tal que: A = L * Lᵗ

    Mis parámetros son:

    Ec_matriz: matriz cuadrada tipo lista de listas
    :return: matriz Ec_L o mensaje de error
    """
    # Obtenemos el número de filas (y columnas) de la matriz
    Ec_n = len(Ec_matriz)

    # Verificamos primero si la matriz es cuadrada.
    for Ec_i in range(Ec_n):
        for Ec_j in range(Ec_i, Ec_n):
            # Si el valor no coincide con su simétrico, no se puede usar Cholesky
            if Ec_matriz[Ec_i][Ec_j] != Ec_matriz[Ec_j][Ec_i]:
                print("SALIDA: La matriz no es simétrica, no se puede aplicar Cholesky.")
                return None

    # Aqui inicializamos la matriz triangular inferior L
    Ec_L = [[0 for _ in range(Ec_n)] for _ in range(Ec_n)]

    # En el paso 2 realizamos la descomposición de Cholesky
    for Ec_i in range(Ec_n):
        for Ec_j in range(Ec_i + 1):
            # Calculamos la sumatoria L[i][k] * L[j][k] desde k = 0 hasta j-1
            Ec_suma = 0
            for Ec_k in range(Ec_j):
                Ec_suma += Ec_L[Ec_i][Ec_k] * Ec_L[Ec_j][Ec_k]

            # Si estamos en la diagonal (i == j), calculamos la raíz
            if Ec_i == Ec_j:
                valor = Ec_matriz[Ec_i][Ec_i] - Ec_suma

                # Validamos que el valor dentro de la raíz sea positivo
                if valor <= 0:
                    print("SALIDA: La matriz no es definida positiva (raíz de negativo o cero).")
                    return None

                # Calculamos L[i][i] = sqrt(valor)
                Ec_L[Ec_i][Ec_j] = valor ** 0.5
            else:
                # Si estamos debajo de la diagonal, usamos la fórmula:
                Ec_L[Ec_i][Ec_j] = (Ec_matriz[Ec_i][Ec_j] - Ec_suma) / Ec_L[Ec_j][Ec_j]

    # Finalmente devolvemos la matriz triangular inferior L
    return Ec_L


A continuación un ejemplo (Pueden editar con cualquier matriz):

In [59]:
# Ejemplo para descomposición por Cholesky
Ec_A = [
    [2, -1, 1],
    [-3, 3, 9],
    [6, -6, -6]
]

Ec_L = Ec_cholesky(Ec_A)

if Ec_L is not None:
    print("SALIDA: Descomposición Cholesky")
    for Ec_fila in Ec_L:
        print(Ec_fila)

SALIDA: La matriz no es simétrica, no se puede aplicar Cholesky.


# <span style="color:red"><strong>Método Gauss-Jacobi</strong></span>



El método de Gauss-Jacobi es una técnica iterativa utilizada para resolver sistemas de ecuaciones lineales del tipo  
$$
A \vec{x} = \vec{b}
$$  
Este método se basa en reorganizar cada ecuación del sistema para despejar una variable en función de las demás, y luego utilizar estos valores para calcular nuevas aproximaciones en cada iteración.

Una característica importante es que realiza todas las operaciones de cada iteración utilizando exclusivamente los valores de la iteración anterior(no actualiza hasta acabar las operaciones de dicha iteración).
Implementa operaciones paralelas, ya que los cálculos de cada incógnita no dependen entre sí dentro de una misma iteración(Lo que hace que sea mas demorosa).


A continuación se observara el código comentado para que se pueda entender lo que realice para mi codificación:

In [40]:
# @autor: Estefano Condoy
# @fecha: 2025-06-28
# @versión: 1.0
# @asignatura: Métodos Numéricos
# @código ralizado basado en el pseudocódigo del Ing. Carlos Ayala

import time  # Con esto medimos el tiempo de ejecución real
from tabulate import tabulate  # Solo se utilizara para imprimir la tabla de iteraciones

def EcTruncar(valor, decimales):
    """
    Con esta función truncaremos una cantidad fija de deciamales (No ocupo el del anterior bimestre porque esta en el otro notebook).
    Los parametros son:
    valor: Valor numérico a truncar
    decimales: Cantidad de decimales a conservar
    :return: Número truncado
    """
    EcFactor = 10.0 ** decimales
    return int(valor * EcFactor) / EcFactor

def EcGaussJacobi(EcA, EcB, EcX0, EcTOL, EcNmax, EcDecimales):
    """
    Creo esté código para resolver el tipo Ax=B con el método de Gauss-Jacobi para resolver sistemas lineales del tipo Ax = b.

    Los parametros que voy a utilizar son :

    EcA: Matriz de coeficientes A
    EcB: Vector de términos independientes b
    EcX0: Aproximación inicial para x
    EcTOL: Tolerancia para la norma ||x - x0||
    EcNmax: Número máximo de iteraciones
    EcDecimales: Decimales a truncar en la salida
    :return: Solución aproximada si converge, o None si no converge
    """

    EcN = len(EcA)  # Número de incógnitas
    EcX = [0.0 for _ in range(EcN)]  # Vector auxiliar para nuevos valores de x
    EcK = 1  # Con esto contamos las iteraciones
    EcTabla = []  # Esta es la lista donde se almacenan los resultados de cada iteración

    EcInicio = time.time()  # Iniciamos el tempo de ejecución
    
    while EcK <= EcNmax:
        # En el paso tres Calculamos los nuevos valores de x[i]
        for i in range(EcN):
            EcSuma = 0.0
            for j in range(EcN):
                if j != i:
                    EcSuma += EcA[i][j] * EcX0[j]
            EcX[i] = (EcB[i] - EcSuma) / EcA[i][i]

        # En el paso cuatro calculamos la norma ||x - x0|| para verificar convergencia (Elegi esta porque es la más facil de implementar)
        EcNorma = max(abs(EcX[i] - EcX0[i]) for i in range(EcN))

        # Almacenamos las iteración en la tabla (se truncan los valores)
        EcFila = [EcK] + [EcTruncar(val, EcDecimales) for val in EcX] + [round(EcNorma, EcDecimales)]
        EcTabla.append(EcFila)

        # Aquí verificamos si el método converge
        if EcNorma < EcTOL:
            EcFin = time.time()  # Fin de la ejecución
            print("\nEl procedimiento fue exitoso.")
            
            # Usamos de tabulate ya que esta función permite imprimir la tabla de iteraciones en formato de cuadrícula.
            # Cada fila muestra: número de iteración, valores de las variables, y el error ||x - x0||
            EcEncabezado = ["Iteración"] + [f"x{i+1}" for i in range(EcN)] + ["||x - XO||"]
            print("\nIteraciones:")
            print(tabulate(EcTabla, headers=EcEncabezado, tablefmt="grid"))

            # Mostramos la solución final truncada
            print(f"\nTiempo total de ejecución: {round(EcFin - EcInicio, 6)} segundos")
            
            # Retornanos la solución truncada
            return [EcTruncar(val, EcDecimales) for val in EcX]

        # En el paso cinco y seis se prepara para la siguiente iteración
        EcX0 = EcX[:]  # Copia superficial que es segura aquí porque EcX solo contiene números
        EcK += 1

    # En el paso 7 si se excede el número de iteraciones, se informa y termina
    EcFin = time.time()
    print("\nEl procedimiento no fue exitoso: se exedio las iteraciones ")

    # Mostramos la tabla de iteraciones

    EcEncabezado = ["Iteración"] + [f"x{i+1}" for i in range(EcN)] + ["||x - XO||"]
    print("\nIteraciones:")
    print(tabulate(EcTabla, headers=EcEncabezado, tablefmt="grid"))
    print(f"\nTiempo total de ejecución: {round(EcFin - EcInicio, 6)} segundos")

    return None


A continuación un ejemplo (Pueden editar con cualquier matriz):

In [48]:
EcA = [[10, 2, 1],
       [2, 20, -2],
       [-2, 3, 10]]

EcB = [9, -44, 22]
EcX0 = [0, 0, 0]
EcTOL = 1e-2
EcNmax = 100
EcDecimales = 4

EcResultado = EcGaussJacobi(EcA, EcB, EcX0, EcTOL, EcNmax, EcDecimales)

if EcResultado:
    print("\nSolución final aproximada con Gauss Jacobi:", EcResultado)



El procedimiento fue exitoso.

Iteraciones:
+-------------+--------+---------+--------+--------------+
|   Iteración |     x1 |      x2 |     x3 |   ||x - XO|| |
+=============+========+=========+========+==============+
|           1 | 0.9    | -2.2    | 2.2    |       2.2    |
+-------------+--------+---------+--------+--------------+
|           2 | 1.1199 | -2.07   | 3.04   |       0.84   |
+-------------+--------+---------+--------+--------------+
|           3 | 1.01   | -2.008  | 3.045  |       0.11   |
+-------------+--------+---------+--------+--------------+
|           4 | 0.9971 | -1.9965 | 3.0044 |       0.0406 |
+-------------+--------+---------+--------+--------------+
|           5 | 0.9988 | -1.9992 | 2.9983 |       0.006  |
+-------------+--------+---------+--------+--------------+

Tiempo total de ejecución: 6.9e-05 segundos

Solución final aproximada con Gauss Jacobi: [0.9988, -1.9992, 2.9983]


# <span style="color:red"><strong>Método Gauss-Seidel</strong></span>


El método de Gauss-Seidel también es una técnica iterativa para resolver sistemas lineales  
$$
A \vec{x} = \vec{b}
$$  
es similar al método de Gauss-Jacobi. Sin embargo, su diferencia principal radica en que utiliza de inmediato los nuevos valores calculados dentro de la misma iteración para actualizar el resto de las incógnitas (Es secuencial y actualiza rápido).

Este enfoque secuencial lo hace más eficiente en términos de convergencia, ya que incorpora la información más reciente disponible, lo cual suele reducir el número total de iteraciones. 


A continuación se observara el código comentado para que se pueda entender lo que realice para mi codificación:

In [ ]:
# @autor: Estefano Condoy
# @fecha: 2025-06-29
# @versión: 1.0
# @asignatura: Métodos Numéricos
# @descripción: Implementación del método Gauss-Seidel con tabla de iteraciones y tiempo de ejecución

import time
from tabulate import tabulate  # Solo para mostrar tabla

def EcGaussSeidel(EcA, EcB, EcX0, EcTOL, EcNmax, EcDecimales):
    """
    Método iterativo de Gauss-Seidel para resolver sistemas de ecuaciones lineales Ax = b.
    
    EcA: Para la matriz de coeficientes
    EcB: Para el vector independiente
    :param EcX0: Vector inicial
    :param EcTOL: Tolerancia para error ||x - x0||
    :param EcNmax: Número máximo de iteraciones
    :param EcDecimales: Número de decimales para truncar
    :return: Solución aproximada o None si no converge
    """
    EcN = len(EcA)
    EcX = EcX0[:]  # Copia la iteracion Inicial
    EcTabla = []   # Da la tabla de Iteraciones
    EcK = 1        # Esto hace el conteo de iteraciones.

    EcInicio = time.time()  # Iniciamos el cronómetro para medir el tiempo de ejecución

    while EcK <= EcNmax:
        EcXAnterior = EcX[:]  # Con esto guardamos los valores anteriores de x para calcular el error

        # En el paso tres actualizamos x[i] usando valores nuevos y viejos
        for i in range(EcN):
            EcSuma1 = sum(EcA[i][j] * EcX[j] for j in range(i))            # Los valores ya actualizados)
            EcSuma2 = sum(EcA[i][j] * EcXAnterior[j] for j in range(i+1, EcN))  # j=i+1 hasta n-1 (valores aún sin actualizar)
            EcX[i] = (EcB[i] - EcSuma1 - EcSuma2) / EcA[i][i]

        # En el paso cuatro calculamos la norma ||x - x0|| para verificar convergencia (Elegi esta porque es la más facil de implementar)
        EcNorma = max(abs(EcX[i] - EcXAnterior[i]) for i in range(EcN))

        # Con esto agregamos la fila de la iteración a la tabla
        EcFila = [EcK] + [EcTruncar(val, EcDecimales) for val in EcX] + [round(EcNorma, EcDecimales)]
        EcTabla.append(EcFila)

        # Este if verifica si el método converge
        if EcNorma < EcTOL:
            EcFin = time.time()
            # Aquí finalizamos el cronómetro y mostramos el mensaje de éxito
            print("\nEl procedimiento fue exitoso.")
            EcEncabezado = ["Iteración"] + [f"x{i+1}" for i in range(EcN)] + ["||x - XO||"]
            print("\nIteraciones:")
            print(tabulate(EcTabla, headers=EcEncabezado, tablefmt="grid"))
            print(f"\nTiempo total de ejecución: {round(EcFin - EcInicio, 6)} segundos")
            return [EcTruncar(val, EcDecimales) for val in EcX]

        EcK += 1  # Esto en el paso cinco y seis  incrementa el contador de iteraciones

    # En el paso siete si se excede el número máximo de iteraciones, se informa y termina
    EcFin = time.time()
    print("\nEl procedimiento no fue exitoso: se excedió las iteraciones.")
    EcEncabezado = ["Iteración"] + [f"x{i+1}" for i in range(EcN)] + ["||x - XO||"]
    print("\nIteraciones:")
    print(tabulate(EcTabla, headers=EcEncabezado, tablefmt="grid"))
    print(f"\nTiempo total de ejecución: {round(EcFin - EcInicio, 6)} segundos")
    return None


A continuación un ejemplo (Pueden editar con cualquier matriz):

In [55]:

EcA = [[10, 2, 1],
       [2, 20, -2],
       [-2, 3, 10]]

EcB = [9, -44, 22]
EcX0 = [0, 0, 0]
EcTOL = 1e-2
EcNmax = 100
EcDecimales = 4

EcSolucion = EcGaussSeidel(EcA, EcB, EcX0, EcTOL, EcNmax, EcDecimales)

if EcSolucion:
    print("\nSolución final aproximada con Gauss Seidel:", EcSolucion)



El procedimiento fue exitoso.

Iteraciones:
+-------------+--------+---------+--------+--------------+
|   Iteración |     x1 |      x2 |     x3 |   ||x - XO|| |
+=============+========+=========+========+==============+
|           1 | 0.9    | -2.29   | 3.067  |       3.067  |
+-------------+--------+---------+--------+--------------+
|           2 | 1.0512 | -1.9984 | 3.0097 |       0.2916 |
+-------------+--------+---------+--------+--------------+
|           3 | 0.9987 | -1.9988 | 2.9994 |       0.0526 |
+-------------+--------+---------+--------+--------------+
|           4 | 0.9998 | -2      | 2.9999 |       0.0012 |
+-------------+--------+---------+--------+--------------+

Tiempo total de ejecución: 8.5e-05 segundos

Solución final aproximada con Gauss Seidel: [0.9998, -2.0, 2.9999]
